language: node_js
node_js:
# - '6'
- '8'
- node
branches:
  only:
  - master
  # npm version tags
  - /^v\d+\.\d+\.\d+$/
cache:
  directories:
  - "$HOME/.npm"
before_install:
- npm config set spin false
- if [ "$TRAVIS_NODE_VERSION" = "6" ]; then
    npm install -g npm@5;
  fi
script:
- # npm run lint
- npm test
